sets up messages and info to send to slack at the end instead of on each occurrence re-arranges some thing so that we exit the job completely instead of needing to check the status of previous steps at every step

diff --git a/.github/workflows/updates.yaml b/.github/workflows/updates.yaml
--- a/.github/workflows/updates.yaml
+++ b/.github/workflows/updates.yaml
@@ -162,14 +162,22 @@ jobs:
         steps: 
             # 1. Make sure the template repo exists 
             - name: Step 1. Verify the template repo exists
+              id: template-repo-exists
               run: | 
-                echo "Job status is ${{ job.status }}"
-                repoData=$(gh api "/repos/${REPOOWNER}/${{ matrix.template }}")
+                # echo "::set-output name=slack_runurl::https://github.com/${REPOOWNER}/template-builder/actions/runs/${GITHUB_RUN_ID}"
+                # Why curl instead of the gh cli? Because on not found, the gh cli will return an exit code of 1 which immediately fails the step and the job
+                repoData=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${REPOOWNER}/${{ matrix.template }})
                 repoID=$(echo "$repoData" | jq '.id')
                 repoFound=$(echo "$repoData" | jq '.message')
                 if [[ -z "$repoID" || "$repoFound" = "Not Found"  ]]; then
-                  echo "The template repo for ${{ matrix.template }} doesn't exist and will need to be created before I can help you."
+                  message="The template repo for ${{ matrix.template }} doesn't exist and will need to be created before I can help you."
+                  echo "::error ::${message}"
+                  echo "::set-env name=SLACK_MSG::${message}"
+                  echo "::set-env name=SLACK_PRURL::no-pr"
+                  echo "::set-env name=SLACK_STATUS::skip"
                   exit 11;
+                else
+                  echo "::set-output name=slackmsg::''"
                 fi
             # 0. Install tools and dependencies.
             - uses: actions/checkout@v2
@@ -200,42 +208,32 @@ jobs:
             - name: Step 2. Check if update branch exists on GH
               id: branchstatus
               run: |
-                echo "Job status is ${{ job.status }}"
-                echo "dealing with template ${{ matrix.template }} for owner ${REPOOWNER}"
                 STATUS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${REPOOWNER}/${{ matrix.template }}/branches/$UPDATES_BRANCH)
                 branchStatus=$( echo $STATUS | jq -r '.message' )
-                echo "branch status is ${branchStatus}"
-                echo "::set-output name=status::$( echo $STATUS | jq -r '.message' )"
-            - name: Step 3. Exit if update branch exists
-              if: steps.branchstatus.outputs.status != 'Branch not found'
-              run: |
-                echo "Job status is ${{ job.status }}"
-                TEMPLATE=${{ matrix.template }} 
-                MESSAGE="Update branch already exists. Skipping template until investigation on open branch (https://github.com/${REPOOWNER}/$TEMPLATE/tree/$UPDATES_BRANCH) is closed."
-                echo "$MESSAGE"
-                RUN_URL=https://github.com/${REPOOWNER}/template-builder/actions/runs/$GITHUB_RUN_ID
-                PR_URL='no pr'
-                THREAD_ID=${{ needs.build.outputs.threadts }}
-                RESULT=$(SLACK_BOT_TOKEN=$SLACK_TOKEN CHANNEL_ID=$SLACK_CHANNEL_ID THREAD_ID=$THREAD_ID poetry run python utils/slack_notifier.py skip $TEMPLATE "$RUN_URL" "$PR_URL" "$MESSAGE")
-                exit 1; # should fail the remaining steps
 
-            # 4. Run the update tasks through template-builder.
-            - name: 'Step 4. Cleanup template build area'
-              if: steps.branchstatus.outputs.status == 'Branch not found'
+                if [[ 'Branch not found' != "$branchStatus" ]]; then
+                  MESSAGE="Update branch already exists. Skipping template until investigation on open branch (https://github.com/${REPOOWNER}/$TEMPLATE/tree/$UPDATES_BRANCH) is closed."
+                  echo "::error ::${message}"
+                  echo "::set-env name=SLACK_MSG::${message}"
+                  echo "::set-env name=SLACK_PRURL::no-pr"
+                  echo "::set-env name=SLACK_STATUS::skip"
+                  exit 12; # should fail the remaining steps
+                fi
+
+                echo "::set-output name=status::$( echo $STATUS | jq -r '.message' )"
+
+            # 3. Run the update tasks through template-builder.
+            - name: 'Step 3. Cleanup template build area'
               run: |
-                echo "Job status is ${{ job.status }}"
                 python -m poetry run doit cleanup:${{ matrix.template }}
-            - name: 'Step 5. Initialize template build'
-              if: steps.branchstatus.outputs.status == 'Branch not found'
+            - name: 'Step 4. Initialize template build'
               uses: actions/checkout@v2
               with:
                 token: ${{ secrets.DEVREL_TOKEN }}
                 repository: ${{ env.REPOOWNER }}/${{ matrix.template }}
                 path: templates/${{ matrix.template }}/build
-            - name: 'Step 6. Initialize remote'
-              if: steps.branchstatus.outputs.status == 'Branch not found'
+            - name: 'Step 5. Initialize remote'
               run: |
-                echo "Job status is ${{ job.status }}"
                 # Get the remote 
                 export TEMPLATE=${{ matrix.template }}
 
@@ -259,26 +257,21 @@ jobs:
                     echo "Upstream found: $REMOTE_UPSTREAM"
                     git remote add project $REMOTE_UPSTREAM
                 fi
-            - name: 'Step 7. Update'
-              if: steps.branchstatus.outputs.status == 'Branch not found'
+            - name: 'Step 6. Update'
               run: |
                 UPDATES_BRANCH=$UPDATES_BRANCH UPDATE_COMMIT_MSG=$UPDATE_COMMIT_MSG python -m poetry run doit update:${{ matrix.template }}
-            - name: 'Step 8. Platformify'
-              if: steps.branchstatus.outputs.status == 'Branch not found'
+            - name: 'Step 7. Platformify'
               run: |
                 UPDATES_BRANCH=$UPDATES_BRANCH UPDATE_COMMIT_MSG=$UPDATE_COMMIT_MSG python -m poetry run doit platformify:${{ matrix.template }}
-            - name: 'Step 9. Branch'
-              if: steps.branchstatus.outputs.status == 'Branch not found'
+            - name: 'Step 8. Branch'
               run: |
                 UPDATES_BRANCH=$UPDATES_BRANCH UPDATE_COMMIT_MSG=$UPDATE_COMMIT_MSG python -m poetry run doit branch:${{ matrix.template }}
-            - name: 'Step 10. Push'
-              if: steps.branchstatus.outputs.status == 'Branch not found'
+            - name: 'Step 9. Push'
               run: |
                 UPDATES_BRANCH=$UPDATES_BRANCH UPDATE_COMMIT_MSG=$UPDATE_COMMIT_MSG python -m poetry run doit push:${{ matrix.template }}
 
             # 3. Check to see updates have been pushed to a branch.
-            - name: Step 11. Check if updates have been pushed
-              if: steps.branchstatus.outputs.status == 'Branch not found'
+            - name: Step 10. Check if updates have been pushed
               id: pushstatus
               run: |
                 STATUS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${REPOOWNER}/${{ matrix.template }}/branches/$UPDATES_BRANCH)
@@ -286,14 +279,17 @@ jobs:
                 echo "pushed branch status is ${step11}"
 
                 if [[ "${step11}" = "Branch not found" ]]; then
-                  echo "The update branch ${UPDATES_BRANCH} for the template ${{ matrix.template }} was not found. Can't continue without it."
-                  exit 11;
+                  message="The update branch ${UPDATES_BRANCH} for the template ${{ matrix.template }} was not found. Can't create a PR without it."
+                  echo "::error ::${message}"
+                  echo "::set-env name=SLACK_MSG::${message}"
+                  echo "::set-env name=SLACK_PRURL::no-pr"
+                  echo "::set-env name=SLACK_STATUS::skip"
+                  exit 110;
                 else
                   echo "::set-output name=status::$( echo $STATUS | jq -r '.message' )"
                 fi
             # 3a. Verify the repository is set for automerge
             - name: Step 12. Check if auto-merge is enabled for repository
-              if: steps.branchstatus.outputs.status == 'Branch not found' && steps.pushstatus.conclusion == 'success'
               run: |
                 autoMREnabled=$(gh api /repos/${REPOOWNER}/${{ matrix.template }} --jq '.allow_auto_merge')
                 if [[ "${autoMREnabled}" != "true" ]]; then
@@ -303,7 +299,6 @@ jobs:
             # 4. Create pull request from pushed update.
             - name: Step 13. Get template default branch
               id: defaultbranch
-              if: ${{ steps.branchstatus.outputs.status == 'Branch not found' && steps.pushstatus.outputs.status != 'Branch not found' }}
               run: |
                 # Get the default branch.
                 DEFAULT_BRANCH=$(gh api /repos/${REPOOWNER}/${{ matrix.template }} --jq '.default_branch')
@@ -314,7 +309,6 @@ jobs:
             # @todo do we bother to check, or do we just assume it isnt set and attempt to create it anyway? If we attempt to create it and it already
             # exists, it should just return the same values anyway
             - name: Step 14. Add branch protection rules to default branch
-              if: steps.branchstatus.outputs.status == 'Branch not found'
               run: |
                 # For some reason, the following isnt being expanded when we try to use it directly
                 defaultBranch=${{ steps.defaultbranch.outputs.branch }}
@@ -327,7 +321,6 @@ jobs:
             # 4b. Patch the rule we just created
             - name: Step 15. Patch the Branch Protection Rule
               id: branchprotection
-              if: steps.branchstatus.outputs.status == 'Branch not found'
               run: |
                 branchProtectionQuery='query($name: String!, $owner: String!) { repository(owner: $owner, name: $name) { branchProtectionRules(first: 1) { nodes { id } } } }'
                 # @todo this assumes the branch protection rule is ALWAYS the first one. Brittle. Also assumes the rule exists
@@ -356,7 +349,6 @@ jobs:
                 fi
 
             - name: 'Step 16. Open pull request'
-              if: ${{ steps.branchstatus.outputs.status == 'Branch not found' && steps.pushstatus.outputs.status != 'Branch not found' }}
               id: open-pull-request
               run: |
                   TITLE="Scheduled updates."
@@ -390,8 +382,9 @@ jobs:
                   TEMPLATE=${{ matrix.template }} 
                   RUN_URL=https://github.com/${REPOOWNER}/template-builder/actions/runs/$GITHUB_RUN_ID
                   THREAD_ID=${{ needs.build.outputs.threadts }}
-                  PR_URL='no pr'
-                  MESSAGE='Something went wrong. Investigate.'
+                  PR_URL=${SLACK_PRURL}
+                  MESSAGE="Something went wrong. Investigate.\n${SLACK_MSG}"
+                  echo "::warning ::I would send the following warning to slack\n${MESSAGE}"
                   RESULT=$(SLACK_BOT_TOKEN=$SLACK_TOKEN CHANNEL_ID=$SLACK_CHANNEL_ID THREAD_ID=$THREAD_ID poetry run python utils/slack_notifier.py down $TEMPLATE "$RUN_URL" "$PR_URL" "$MESSAGE")
             - name: Step 19. Send successfull workflows to the pull request
               if: ${{ success() && steps.branchstatus.outputs.status == 'Branch not found' }}
