adds REPOOWNER env var so I can point to my testing repos Adds step to check for and enable auto-merge on repo adds step to add branch protection rule to the default branch adds step to patch the branch protection rule to not require a reviewer

diff --git a/.github/workflows/updates.yaml b/.github/workflows/updates.yaml
--- a/.github/workflows/updates.yaml
+++ b/.github/workflows/updates.yaml
@@ -27,6 +27,7 @@ env:
     PYTHON_VERSION: "3.9"
     RUBY_VERSION: "2.7.4"
     BUNDLER_VERSION: "2.2.26"
+    REPOOWNER: "gilzow"
 
 jobs:
     # A. Get the list of templates that will be used in the update (all subdirectories in `templates/`).
@@ -71,7 +72,7 @@ jobs:
           - name: 'Start notification on Slack'
             id: startslack
             run: |
-              RUN_URL=https://github.com/platformsh/template-builder/actions/runs/$GITHUB_RUN_ID
+              RUN_URL=https://github.com/$REPOOWNER/template-builder/actions/runs/$GITHUB_RUN_ID
               THREAD_ID=$(SLACK_BOT_TOKEN=$SLACK_TOKEN CHANNEL_ID=$SLACK_CHANNEL_ID JOB_ID="$JOB_ID" JOB_COLOR=$JOB_COLOR poetry run python utils/slack_notifier.py start $RUN_URL "$START_MESSAGE")
               echo "::set-output name=threadts::$THREAD_ID"
 
@@ -188,18 +189,19 @@ jobs:
             - name: Check if update branch exists on GH
               id: branchstatus
               run: |
-                STATUS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/platformsh-templates/${{ matrix.template }}/branches/$UPDATES_BRANCH)
+                STATUS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${REPOOWNER}/${{ matrix.template }}/branches/$UPDATES_BRANCH)
                 echo "::set-output name=status::$( echo $STATUS | jq -r '.message' )"
             - name: Exit if update branch exists
               if: steps.branchstatus.outputs.status != 'Branch not found'
               run: |
                 TEMPLATE=${{ matrix.template }} 
-                MESSAGE="Update branch already exists. Skipping template until investigation on open branch (https://github.com/platformsh-templates/$TEMPLATE/tree/$UPDATES_BRANCH) is closed."
+                MESSAGE="Update branch already exists. Skipping template until investigation on open branch (https://github.com/${REPOOWNER}/$TEMPLATE/tree/$UPDATES_BRANCH) is closed."
                 echo "$MESSAGE"
-                RUN_URL=https://github.com/platformsh/template-builder/actions/runs/$GITHUB_RUN_ID
+                RUN_URL=https://github.com/${REPOOWNER}/template-builder/actions/runs/$GITHUB_RUN_ID
                 PR_URL='no pr'
                 THREAD_ID=${{ needs.build.outputs.threadts }}
                 RESULT=$(SLACK_BOT_TOKEN=$SLACK_TOKEN CHANNEL_ID=$SLACK_CHANNEL_ID THREAD_ID=$THREAD_ID poetry run python utils/slack_notifier.py skip $TEMPLATE "$RUN_URL" "$PR_URL" "$MESSAGE")
+                exit 1; # should fail the remaining steps
 
             # 2. Run the update tasks through template-builder.
             - name: 'Cleanup'
@@ -211,7 +213,7 @@ jobs:
               uses: actions/checkout@v2
               with:
                 token: ${{ secrets.DEVREL_TOKEN }}
-                repository: platformsh-templates/${{ matrix.template }}
+                repository: ${REPOOWNER}/${{ matrix.template }}
                 path: templates/${{ matrix.template }}/build
             - name: 'Initialize remote'
               if: steps.branchstatus.outputs.status == 'Branch not found'
@@ -261,8 +263,17 @@ jobs:
               if: steps.branchstatus.outputs.status == 'Branch not found'
               id: pushstatus
               run: |
-                STATUS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/platformsh-templates/${{ matrix.template }}/branches/$UPDATES_BRANCH)
+                STATUS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${REPOOWNER}/${{ matrix.template }}/branches/$UPDATES_BRANCH)
                 echo "::set-output name=status::$( echo $STATUS | jq -r '.message' )"
+
+            # 3a. Verify the repository is set for automerge
+            - name: Check if auto-merge is enabled for repository
+              if: steps.branchstatus.outputs.status == 'Branch not found'
+              run: |
+                autoMREnabled=$(gh api /repos/${REPOOWNER}/${{ matrix.template }} --jq '.allow_auto_merge')
+                if [[ "${autoMREnabled}" != "true" ]]; then
+                  gh api -X PATCH /repos/${REPOOWNER}/${{ matrix.template }} --field allow_auto_merge=true
+                fi  
 
             # 4. Create pull request from pushed update.
             - name: Get template default branch
@@ -270,8 +281,57 @@ jobs:
               if: ${{ steps.branchstatus.outputs.status == 'Branch not found' && steps.pushstatus.outputs.status != 'Branch not found' }}
               run: |
                 # Get the default branch.
-                DEFAULT_BRANCH=$(gh api /repos/platformsh-templates/${{ matrix.template }} --jq '.default_branch')
+                DEFAULT_BRANCH=$(gh api /repos/${REPOOWNER}/${{ matrix.template }} --jq '.default_branch')
                 echo "::set-output name=branch::$DEFAULT_BRANCH" 
+
+            # 4a. Check if default branch has branch rules in place
+            # @todo do we bother to check, or do we just assume it isnt set and attempt to create it anyway? If we attempt to create it and it already
+            # exists, it should just return the same values anyway
+            - name: Add branch protection rules to default branch
+              if: steps.branchstatus.outputs.status == 'Branch not found'
+              run: |
+                # we HAVE to set the number of reviewers to 1 as the API will error otherwise
+                protectBranchJSON='{"required_status_checks":{"strict":true,"contexts":["contexts"]},"enforce_admins":true,"required_pull_request_reviews":{"dismiss_stale_reviews":true,"require_code_owner_reviews":false,"required_approving_review_count":1},"restrictions":null}'
+                # @todo do we need to check if the generation of the branch protection was successful? The API should return a 200 if successful, but at this stage
+                # I'm not sure how we access returned response headers from the cli tool
+                echo "${protectBranchJSON}" | gh api -X PUT /repos/gilzow/hugo/branches/master/protection --input -
+            # 4b. Patch the rule we just created
+            - name: Patch the Branch Protection Rule
+              id: branchprotection
+              if: steps.branchstatus.outputs.status == 'Branch not found'
+              run: |
+                branchProtectionQuery="
+                  query(\$name: String!, \$owner: String!) {
+                    repository(owner: \$owner, name: \$name) {
+                      branchProtectionRules(first: 1) {
+                        nodes {
+                                  id
+                                }
+                            }
+                        }
+                    }"
+                # @todo this assumes the branch protection rule is ALWAYS the first one. Brittle. Also assumes the rule exists
+                branchProtectionID=$(gh api graphql -F owner=${REPOOWNER} -F name=${{ steps.defaultbranch.outputs.branch }} -f query=${branchProtectionQuery} --jq '.data.repository.branchProtectionRules.nodes[0].id')
+                if [[ -n "${branchProtectionID}" ]]; then
+                  # patch it so the review check is disabled
+                  # b = branch, p = protection, r = rule, M (at the end) = mutation
+                  bprUpdateReviewersM="
+                    mutation updateBPR(\$bprID:String!) {
+                      updateBranchProtectionRule(input:{
+                        branchProtectionRuleId: \$bprID,
+                        requiredApprovingReviewCount:0
+                      }) {
+                        branchProtectionRule{
+                          id,
+                          requiredApprovingReviewCount
+                        }
+                      }
+                    }"
+
+                    # @todo should we check for success or just go for it?
+                    gh api graphql -F bprID="${branchProtectionID}" -f query="${bprUpdateReviewersM}"
+                fi
+
             - name: 'Open pull request'
               if: ${{ steps.branchstatus.outputs.status == 'Branch not found' && steps.pushstatus.outputs.status != 'Branch not found' }}
               id: open-pull-request
@@ -280,7 +340,7 @@ jobs:
                   BODY="Scheduled updates from template-builder ($(date))."
 
                   # If successful, the cli will return the URL to the created PR.
-                  response=$(gh pr create --head "$UPDATES_BRANCH" --base "${{ steps.defaultbranch.outputs.branch }}" --title "$TITLE" --body "$BODY" --repo platformsh-templates/${{ matrix.template }})
+                  response=$(gh pr create --head "$UPDATES_BRANCH" --base "${{ steps.defaultbranch.outputs.branch }}" --title "$TITLE" --body "$BODY" --repo ${REPOOWNER}/${{ matrix.template }})
                   # If the CLI returns 1, the step will fail.
                   boolPRCreated=$?
                   prRegex="([0-9]+$)"
@@ -297,7 +357,7 @@ jobs:
             - name: Automatically merge only after necessary requirements are met
               if: ${{ steps.branchstatus.outputs.status == 'Branch not found' && steps.open-pull-request.outputs.pull-request-number != '' }}
               run: |
-                  gh pr merge ${{ steps.open-pull-request.outputs.pull-request-number }} --auto --merge --repo=platformsh-templates/${{ matrix.template }}
+                  gh pr merge ${{ steps.open-pull-request.outputs.pull-request-number }} --auto --merge --repo=${REPOOWNER}/${{ matrix.template }}
                   lastcommand=$?
 
             # 6. Catch all failures and successes.
@@ -305,7 +365,7 @@ jobs:
               if: ${{ failure() }}
               run: |
                   TEMPLATE=${{ matrix.template }} 
-                  RUN_URL=https://github.com/platformsh/template-builder/actions/runs/$GITHUB_RUN_ID
+                  RUN_URL=https://github.com/${REPOOWNER}/template-builder/actions/runs/$GITHUB_RUN_ID
                   THREAD_ID=${{ needs.build.outputs.threadts }}
                   PR_URL='no pr'
                   MESSAGE='Something went wrong. Investigate.'
@@ -315,7 +375,7 @@ jobs:
               run: |
                 TEMPLATE=${{ matrix.template }}
                 THREAD_ID=${{ needs.build.outputs.threadts }}
-                RUN_URL=https://github.com/platformsh/template-builder/actions/runs/$GITHUB_RUN_ID
+                RUN_URL=https://github.com/${REPOOWNER}/template-builder/actions/runs/$GITHUB_RUN_ID
 
                 if [ "${{ steps.pushstatus.outputs.status }}" == "Branch not found" ]; then
                     PR_URL="_Template already up-to-date._"
@@ -355,5 +415,5 @@ jobs:
         - name: 'Notify slack when finished'
           run: |
             THREAD_ID=${{ needs.build.outputs.threadts }}
-            RUN_URL=https://github.com/platformsh/template-builder/actions/runs/$GITHUB_RUN_ID
+            RUN_URL=https://github.com/${REPOOWNER}/template-builder/actions/runs/$GITHUB_RUN_ID
             RESULT=$(SLACK_BOT_TOKEN=$SLACK_TOKEN CHANNEL_ID=$SLACK_CHANNEL_ID JOB_ID="$JOB_ID" THREAD_ID=$THREAD_ID JOB_COLOR=$JOB_COLOR poetry run python utils/slack_notifier.py finish $RUN_URL "$START_MESSAGE")
